name: Prebuilt repo + Snyk Security Scanning (OS, Code, Docker, IaC)

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js for installing Snyk 
      uses: actions/setup-node@v2
      with:
        node-version: 16.x

    # Install & prepare Snyk
    - run: npm install --location=global snyk
    - run: npm install snyk-to-html -g
      
    - run: snyk auth ${{ secrets.SNYK_TOKEN }}

    - name: Snyk Code CLI Tests
      run: snyk code test
      continue-on-error: true
    
    - name: Snyk Code reporting
      run: snyk code test --sarif | snyk-to-html>results.html
      continue-on-error: true      
