name: Prebuilt repo + Snyk Security Scanning (OS, Code, Docker, IaC)

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js for installing Snyk 
      uses: actions/setup-node@v2
      with:
        node-version: 16.x

    # Install & prepare Snyk
    - run: npm install --location=global snyk
    - run: npm install snyk-to-html -g
      
    - run: snyk auth ${{ secrets.SNYK_TOKEN }}

    - name: Snyk Code CLI Tests
      run: snyk code test
      continue-on-error: true
    
    - name: Snyk Code reporting
      run: |
          snyk code test --json | snyk-to-html>results.html
          mkdir downloads
          cp -v /home/runner/work/ADDA_demo/ADDA_demo/*.html /home/runner/work/ADDA_demo/ADDA_demo/downloads
      continue-on-error: true
    
    - name: Use the Upload Artifact GitHub Action
      uses: actions/upload-artifact@v2
      with:
          name: results
          path: downloads  

    - name: Snyk Code Sec. tab
      run: |
          snyk code test --sarif-file-output=snyk-code.sarif
          snyk-to-html -i snyk-code.sarif -o results.html
      continue-on-error: true
      
    - name: Upload results to GitHub Code Scanning
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: snyk-code.sarif
