name: Prebuilt repo + Snyk Security Scanning (OS, Code, Docker, IaC)

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js for installing Snyk 
      uses: actions/setup-node@v2
      with:
        node-version: 18.4

    # Install & prepare Snyk
    - run: npm install --location=global snyk
      
    - run: snyk auth ${{ secrets.SNYK_TOKEN }}

    - name: Snyk Code Tests
      run: snyk code test
      continue-on-error: true
